name: garden_dogs
description: dogs support for garden.
version: 2.0.0
repository: https://github.com/misha/dart_garden
resolution: workspace
environment:
  sdk: ^3.10.0
dependencies:
  garden: ^2.0.0
  dogs_core: ^10.1.2
dev_dependencies:
  lints: ^6.1.0
  test: ^1.30.0
scripts:
  analyze: dart analyze
  test: dart test
